class LocatorsPageRegistrationForm:
    FIELD_INPUT_NAME = '[placeholder="First Name"]'
    FIELD_INPUT_LAST_NAME = '[placeholder="Last Name"]'
    FIELD_INPUT_EMAIL = '[id="userEmail"]'
    GENDER_MALE = '[for="gender-radio-1"]'
    FIELD_INPUT_MOBILE_NUMBER = '[id="userNumber"]'
    FIELD_DATE_PICKER = '[id="dateOfBirthInput"]'
    SELECTOR_MONTH_IN_DATE_PICKER = '[class="react-datepicker__month-select"]'
    VALUE_MONTH = './/option[@value="9"]'
    SELECTOR_YEAR_IN_DATE_PICKER = '[class="react-datepicker__year-select"]'
    VALUE_YEAR = '[value="1996"]'
    VALUE_DATE = '[class="react-datepicker__day react-datepicker__day--001"]'
    FIELD_MULTISELECT_SUBJECT = '[id="subjectsInput"]'
    VALUE_MULTISELECT_SUBJECT = './/div[@id="react-select-2-option-0"]'
    CHECK_BOX_HOBBIES_SPORTS = '[for="hobbies-checkbox-1"]'
    FIELD_ADD_PICTURE = './/input[@class="form-control-file"]'
    FIELD_CURRENT_ADDRESS = '[id="currentAddress"]'
    MULTISELECT_STATE = '[id="state"]'
    STATE_NCR = '[id="react-select-3-option-0"]'
    MULTISELECT_CITY = '[id="city"]'
    CITY_DELHI = '[id="react-select-4-option-0"]'
    BUTTON_SUBMIT = '[id="submit"]'
    MODAL_WINDOW_RESULT_SEND = '[class="modal-title h4"]'
    VALUE_MODAL_WINDOW_RESULT_SEND = "tbody"
